# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_image',
            field=models.CharField(default='404', max_length=5000),
            preserve_default=False,
        ),
    ]
